### ISSUE TITLE
Derive +code from master ticket

### ISSUE THREAD

**Issue by vvisigoth** [urbit/urbit-key-generation#64]
Should implement a function that emulates

https://github.com/urbit/arvo/blob/master/sys/vane/jael.hoon#L2292-L2304

And derives a ship's code from the master ticket. This will allow sign in w/ Bridge (via JSON webtoken or similar)

**Comment by joemfb** [comment]
Note the `XX` there, we should review and standardize how that code is derived. We might also want additional features, like the ability to rotate `+code` without rekeying.

**Comment by jtobin** [comment]
I'm going to handle this together with #101.

**Comment by Faolain** [comment]
Hey @jtobin I tried using `generateCode()` for a ship of mine that's in a strange state (I can't access dojo because on Port it says the ship is not on, but I can |hi it from other ships). I have the master ticket & ownership seed but I can't seem to quite get the `+code` correct in order to access landscape via my browser (which unrelated is still somehow present despite Port not loading). I tried sanity checking with another ship that I booted and using that master key as well the code is different the the Port provided access key/+code. I was wondering what parameters I'm using incorrectly in this code, really appreciate it!

```
const VALID_PATH = "m/44'/60'/0'/0/0";

let node = deriveNodeKeys(mnemonic, VALID_PATH);
// Checking here to make sure the address in the node matches what I have on my master ticket paper to confirm that the mnemonic is in fact correct
console.log("node", node);

// Steps start here
let seed = deriveNetworkSeed(mnemonic);
let keys = deriveNetworkKeys(seed);
let code = generateCode(keys);

// Provided code below different than what is given by Port or dojo +code
console.log("code", code);
```

**Comment by jtobin** [comment]
Linking #103.
